DataFileName = "data.json"
SimulateAlarm = false
Debug = false
UrlToCheck = "<todo in custom>"

[Relay]
SendMail = false
EmailTarget = "<todo in custom>"
MailFrom = "<todo in custom>"
Secret = "<todo in custom>"
Host = "<todo in custom>"
User = "<todo in custom>"

[Telegram]
SendTelegram = false
ChatID = -1
APIString = "<todo in custom>"